# This actions runs against every Tag to Prod (or) next tag(Ex:v0.4.6-next.3) to dev
name: Test, publish & deploy

on:
  push:
    tags:
      - v*

jobs:
  # Build & lint & test & publish
  Build_Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      # Run Docker start, node starts
      - name: Build project & docker start
        run: |
          cp sample.config.toml test.config.toml
          chmod -R 777 test/docker/config
          npm run docker:start
          sleep 30

      # Run npm scripts
      - name: npm ci & lint & test
        run: |
          npm ci
          npm run lint
          npm test
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc

      - run: npm publish --access public --tag next
        if: contains(github.ref, '-next.')
      - run: npm publish --access public
        if: contains(github.ref, '-next.') != true

  # Dev Deployment
  DeployDev:
    if: contains(github.ref, '-next.')
    name: Deploy to Dev
    needs: [Build_Publish]
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - uses: appleboy/ssh-action@master
        env:
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
        with:
          host: ${{secrets.SSH_NEXT_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          port: 22
          script: ./update_reload_next
  # Prod Deployment
  ProdDeploy:
    if: contains(github.ref, '-next.') != true
    name: Deploy to Production
    needs: [Build_Publish]
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: appleboy/ssh-action@master
        env:
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
        with:
          host: ${{secrets.SSH_NEXT_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          port: 22
          script: ./update_reload
