# This actions runs against every Pull request(Include Draft)
name: Test

on:
  push:
    branches: '**'

jobs:
  test:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/') != true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: cp sample.config.toml test.config.toml
      - run: chmod -R 777 test/docker/config
      - run: yarn docker:start
      - run: sleep 30
      - run: yarn install --immutable
      - run: yarn run lint
      - run: yarn test
      - name: Collect docker logs on failure
        if: ${{ failure() }}
        uses: jwalton/gh-docker-logs@v1
        with:
          dest: './docker-logs'
      - name: Tar logs
        if: ${{ failure() }}
        run: tar cvzf ./docker-logs.tgz ./docker-logs
      - name: Upload logs to GitHub
        if: ${{ failure() }}
        uses: actions/upload-artifact@master
        with:
          name: docker-logs.tgz
          path: ./docker-logs.tgz
